[default]
FLASK_ENV = "development"
FLASK_APP = "pyblog.app:create_app"
DEBUG = "True"
SQLALCHEMY_TRACK_MODIFICATIONS = "False"
TITLE = "PyBlog"
EXTENSIONS = [
    "pyblog.extensions.database:init_app",
    "pyblog.extensions.migration:init_app",
    "pyblog.extensions.auth:init_app",
    "pyblog.blueprints.user:init_app",
    "pyblog.blueprints.main:init_app",
    "pyblog.blueprints.posts:init_app",
    "pyblog.blueprints.jinja_env:init_app",
]