[default]
SQLALCHEMY_DATABASE_URI = "sqlite:///storage.db"
SECRET_KEY = "generate one with `openssl rand -base64 32`"
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = 'True'
MAIL_USERNAME = 'mail_username@gmail.com'
MAIL_PASSWORD = 'mail_password'

[production]
SQLALCHEMY_DATABASE_URI = "dialect+driver://username:password@host:port/database"