[default]
# SQLALCHEMY_DATABASE_URI_SQLITE = "sqlite:///storage.db"
SQLALCHEMY_DATABASE_URI = "dialect+driver://username:password@host:port/database"
SECRET_KEY = "generate one with `openssl rand -base64 32`"